CHPL_MAKE_HOME = /fs/mashie/hzhang86/program/Chapel/chapel-1.9.0

TMPDIRNAME = .
BINNAME = a.out

TMPBINNAME = ./a.out.tmp
COMP_GEN_CFLAGS = $(IEEE_FLOAT_GEN_CFLAGS) 
COMP_GEN_LFLAGS = 
TAGS_COMMAND = 
CHPLSRC = \
	./_main.c \


LIBS =


include $(CHPL_MAKE_HOME)/runtime/etc/Makefile.exe


