CHPL_MAKE_HOME = /export/home/hzhang86/chapel/chapel

TMPDIRNAME = example/Testllvm/cOutput/
BINNAME = a.out

TMPBINNAME = example/Testllvm/cOutput//a.out.tmp
COMP_GEN_CFLAGS = $(IEEE_FLOAT_GEN_CFLAGS) 
COMP_GEN_LFLAGS = 
TAGS_COMMAND = 
CHPLSRC = \
	example/Testllvm/cOutput//_main.c \


LIBS =


include $(CHPL_MAKE_HOME)/runtime/etc/Makefile.exe


