CHPL_MAKE_HOME = /export/home/hzhang86/chapel/chapel

TMPDIRNAME = llvm-bcs/
SKIP_COMPILE_LINK = skip
BINNAME = experiment

TMPBINNAME = llvm-bcs//experiment.tmp
COMP_GEN_CFLAGS = $(DEBUG_CFLAGS) $(IEEE_FLOAT_GEN_CFLAGS) 
COMP_GEN_LFLAGS = 
TAGS_COMMAND = 
CHPLSRC = \
	llvm-bcs//chpl__module.bc \


LIBS =
DEBUG = 1


include $(CHPL_MAKE_HOME)/runtime/etc/Makefile.exe


