CHPL_MAKE_HOME = /export/home/hzhang86/chapel/chapel

TMPDIRNAME = ./
SKIP_COMPILE_LINK = skip
BINNAME = add

TMPBINNAME = .//add.tmp
COMP_GEN_CFLAGS = $(DEBUG_CFLAGS) $(IEEE_FLOAT_GEN_CFLAGS) 
COMP_GEN_LFLAGS = 
TAGS_COMMAND = 
CHPLSRC = \
	.//chpl__module.bc \


LIBS =
DEBUG = 1


include $(CHPL_MAKE_HOME)/runtime/etc/Makefile.exe


