CHPL_MAKE_HOME = /export/home/hzhang86/chapel/chapel

TMPDIRNAME = example/llvm-bcs/zeroOpt/
SKIP_COMPILE_LINK = skip
BINNAME = example/experiment

TMPBINNAME = example/llvm-bcs/zeroOpt//experiment.tmp
COMP_GEN_CFLAGS = $(DEBUG_CFLAGS) $(IEEE_FLOAT_GEN_CFLAGS) 
COMP_GEN_LFLAGS = 
TAGS_COMMAND = 
CHPLSRC = \
	example/llvm-bcs/zeroOpt//chpl__module.bc \


LIBS =
DEBUG = 1


include $(CHPL_MAKE_HOME)/runtime/etc/Makefile.exe


