CHPL_MAKE_HOME = /export/home/hzhang86/chapel/chapel

TMPDIRNAME = Testllvm/hello4/
SKIP_COMPILE_LINK = skip
BINNAME = a.out

TMPBINNAME = Testllvm/hello4//a.out.tmp
COMP_GEN_CFLAGS = $(IEEE_FLOAT_GEN_CFLAGS) 
COMP_GEN_LFLAGS = 
TAGS_COMMAND = 
CHPLSRC = \
	Testllvm/hello4//chpl__module.bc \


LIBS =


include $(CHPL_MAKE_HOME)/runtime/etc/Makefile.exe


